apiVersion: v1
kind: Secret
metadata:
  name: {{ include "codeshield.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "codeshield.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
data: {}

