{{- if .Values.explorer.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: dytallix-explorer
spec:
  minAvailable: {{ .Values.explorer.pdb.minAvailable }}
  selector:
    matchLabels:
      app.kubernetes.io/name: dytallix-lean-launch
      app.kubernetes.io/component: explorer
{{- end }}

