{{- if .Values.rpc.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: dytallix-rpc
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: dytallix-rpc
  minReplicas: {{ .Values.rpc.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.rpc.autoscaling.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.rpc.autoscaling.targetCPUUtilizationPercentage }}
{{- end }}

