global:
  scrape_interval: 5s

scrape_configs:
  - job_name: dyt-node
    metrics_path: /metrics
    static_configs:
      - targets: ["localhost:3030"]
        labels:
          service: node

  - job_name: dyt-api
    metrics_path: /metrics
    static_configs:
      - targets: ["localhost:8787"]
        labels:
          service: api-server

  - job_name: dyt-ai
    metrics_path: /metrics
    static_configs:
      - targets: ["localhost:7000"]
        labels:
          service: ai-service

rule_files:
  - alerts.yml

