{{- if .Values.explorer.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "dytallix.fullname" . }}-explorer
spec:
  selector:
    component: explorer
    app: {{ include "dytallix.fullname" . }}
  ports:
    - name: http
      port: {{ .Values.explorer.service.port }}
      targetPort: {{ .Values.explorer.service.port }}
{{- end }}