{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "dytallix.fullname" . }}
  labels:
    {{- include "dytallix.labels" . | nindent 4 }}
{{- end }}